// TailGrids component category definitions
// Based on TailGrids' six main categories

export const componentCategories = {
  CoreComponents: [
    "buttons",
    "checkboxes", 
    "accordions",
    "alerts",
    "badges",
    "breadcrumbs",
    "dropdowns",
    "forms",
    "inputs",
    "labels",
    "links",
    "lists",
    "progress-bars",
    "radio-buttons",
    "switches",
    "tabs",
    "tooltips"
  ],
  ApplicationUI: [
    "blogs",
    "cards", 
    "contacts",
    "footers",
    "headers",
    "modals",
    "navbars",
    "pagination",
    "sidebars",
    "tables",
    "timelines"
  ],
  MarketingUI: [
    "hero-sections",
    "features",
    "pricing-tables", 
    "testimonials",
    "call-to-action",
    "about-sections",
    "team-sections",
    "contact-sections",
    "newsletter-signup",
    "social-proof",
    "faq-sections",
    "landing-page-headers"
  ],
  ECommerce: [
    "product-grids",
    "product-cards",
    "checkout-forms",
    "shopping-carts",
    "product-details",
    "category-filters",
    "search-bars",
    "wishlist",
    "order-tracking",
    "payment-forms",
    "invoice-templates",
    "product-reviews",
    "comparison-tables",
    "discount-banners",
    "shipping-info",
    "return-policy",
    "customer-support"
  ],
  Dashboard: [
    "charts",
    "calendars", 
    "profiles",
    "menus",
    "statistics-cards",
    "data-tables",
    "user-management",
    "settings-panels",
    "notification-panels",
    "activity-feeds",
    "file-managers",
    "task-lists",
    "analytics-widgets",
    "report-generators",
    "admin-headers",
    "dashboard-sidebars"
  ],
  AIComponents: [
    "ai-headers",
    "ai-navbars",
    "ai-generators",
    "chat-interfaces",
    "ai-features",
    "machine-learning-showcases"
  ]
};
